# Vertical Candidate List
Vertical Candidate List=False
# Use Per Screen DPI
PerScreenDPI=True
# Use mouse wheel to go to prev or next page
WheelForPaging=True
# Font
Font="JetBrainsMono Nerd Font Mono 10"
# Menu Font
MenuFont="JetBrainsMonoNL Nerd Font Mono 10"
# Tray Font
TrayFont="JetBrainsMono Nerd Font Mono 10"
# Tray Label Outline Color
TrayOutlineColor=#44475a
# Tray Label Text Color
TrayTextColor=#f8f8f2
# Prefer Text Icon
PreferTextIcon=False
# Show Layout Name In Icon
ShowLayoutNameInIcon=True
# Use input method language to display text
UseInputMethodLangaugeToDisplayText=True
# Theme
Theme=dracula
